spring.application.name=schedula_backend

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/schedula

# Server
server.port=8080

# JWT Configuration
jwt.secret=SchedulaSecretKeyForJwtTokenGeneration123456fnvnslvnslvnlfnvlfsnvlsnvlfsnlvnslvnslnvlfsnvlnfslvnflvnslnvlfsnvlnlvnflvnldfnldfnlbndljndlbnldnbldfnblndflbndlb
jwt.expiration=86400000